---
- name: Learning to target windows machines
  hosts: winbox
  gather_facts: no # does this work on windows?

  vars_prompt:
          - name: ansible_ssh_pass
            prompt: What is the password to log into this windows machine?
            private: yes

  vars:
          nasa_apod: https://www.nasa.gov/sites/default/files/thumbnails/image/apod.jpg

  tasks:
          - name: Get some cool background graphics
            win_get_url:
                    url: "{{ nasa_apod }}"
                    dest: C:\Users\Galileo\Desktop\nasa_apod.jpg
